steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "Build image"
    args:
      - "build"
      - "-t"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/aegisshield:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "Push image"
    args:
      - "push"
      - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/aegisshield:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: "Deploy service"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "aegisshield"
      - "--image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/aegisshield:$COMMIT_SHA"
      - "--region=europe-west1"
      - "--platform=managed"
      - "--clear-env-vars"
      - "--clear-secrets"
      - "--no-allow-unauthenticated"
      - "--quiet"

images:
  - "europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/aegisshield:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
